Practical No 1
  Predict the price of the Uber ride from a given pickup point to the agreed drop-off location.
Perform following tasks:
1.  Pre-process the dataset.
2.  Identify outliers.
3.  Check the correlation.
4.  Implement linear regression and random forest regression models.
5.  Evaluate the models and compare their respective scores like R2, RMSE, etc.
Dataset link: https://www.kaggle.com/datasets/yasserh/uber-fares-dataset

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("uber.csv")
#insert the daa in df


In [ ]:
df.head()
#seeing the top 5

Unnamed: 0                            key  fare_amount  \
0    24238194    2015-05-07 19:52:06.0000003          7.5   
1    27835199    2009-07-17 20:04:56.0000002          7.7   
2    44984355   2009-08-24 21:45:00.00000061         12.9   
3    25894730    2009-06-26 08:22:21.0000001          5.3   
4    17610152  2014-08-28 17:47:00.000000188         16.0   

           pickup_datetime  pickup_longitude  pickup_latitude  \
0  2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1  2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2  2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3  2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4  2014-08-28 17:47:00 UTC        -73.925023        40.744085   

   dropoff_longitude  dropoff_latitude  passenger_count  
0         -73.999512         40.723217                1  
1         -73.994710         40.750325                1  
2         -73.962565         40.772647                1  
3         -73.965316         40.803349                3  
4         -73.973082         40.761247                5

In [ ]:
df.tail()
#seeing the last 5

Unnamed: 0                           key  fare_amount  \
199995    42598914  2012-10-28 10:49:00.00000053          3.0   
199996    16382965   2014-03-14 01:09:00.0000008          7.5   
199997    27804658  2009-06-29 00:42:00.00000078         30.9   
199998    20259894   2015-05-20 14:56:25.0000004         14.5   
199999    11951496  2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
199995  2012-10-28 10:49:00 UTC        -73.987042        40.739367   
199996  2014-03-14 01:09:00 UTC        -73.984722        40.736837   
199997  2009-06-29 00:42:00 UTC        -73.986017        40.756487   
199998  2015-05-20 14:56:25 UTC        -73.997124        40.725452   
199999  2010-05-15 04:08:00 UTC        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1

In [ ]:
df.isnull().sum()
#how many the null is in the data set
#here 2null value in the one in dropoff_long one in dropoff_lati

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [ ]:
df.describe()
#desrib the dataset of

Unnamed: 0    fare_amount  pickup_longitude  pickup_latitude  \
count  2.000000e+05  200000.000000     200000.000000    200000.000000   
mean   2.771250e+07      11.359955        -72.527638        39.935885   
std    1.601382e+07       9.901776         11.437787         7.720539   
min    1.000000e+00     -52.000000      -1340.648410       -74.015515   
25%    1.382535e+07       6.000000        -73.992065        40.734796   
50%    2.774550e+07       8.500000        -73.981823        40.752592   
75%    4.155530e+07      12.500000        -73.967154        40.767158   
max    5.542357e+07     499.000000         57.418457      1644.421482   

       dropoff_longitude  dropoff_latitude  passenger_count  
count      199999.000000     199999.000000    200000.000000  
mean          -72.525292         39.923890         1.684535  
std            13.117408          6.794829         1.385997  
min         -3356.666300       -881.985513         0.000000  
25%           -73.991407         40.733823         1.000000  
50%           -73.980093         40.753042         1.000000  
75%           -73.963658         40.768001         2.000000  
max          1153.572603        872.697628       208.000000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.shape
# seeing the number of row and col

(200000, 9)

In [ ]:
df = df.dropna()
#droping the two null or all the null value

In [ ]:
df.isnull().sum()
# after droping the null there is no null value

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [ ]:
x = df[['pickup_longitude','pickup_latitude','dropoff_longitude','dropoff_latitude','passenger_count']]
#creating the x variable from the makeing the subset of main data set
# for using the x for traig and testing

In [ ]:
x
#prit the x

pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.999817        40.738354         -73.999512   
1             -73.994355        40.728225         -73.994710   
2             -74.005043        40.740770         -73.962565   
3             -73.976124        40.790844         -73.965316   
4             -73.925023        40.744085         -73.973082   
...                  ...              ...                ...   
199995        -73.987042        40.739367         -73.986525   
199996        -73.984722        40.736837         -74.006672   
199997        -73.986017        40.756487         -73.858957   
199998        -73.997124        40.725452         -73.983215   
199999        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  
0              40.723217                1  
1              40.750325                1  
2              40.772647                1  
3              40.803349                3  
4              40.761247                5  
...                  ...              ...  
199995         40.740297                1  
199996         40.739620                1  
199997         40.692588                2  
199998         40.695415                1  
199999         40.768793                1  

[199999 rows x 5 columns]

In [ ]:
y = df['fare_amount']
#creating the y variable from the makeing the subset of main data set
# for using the yfor traig and testing




In [ ]:
y

0          7.5
1          7.7
2         12.9
3          5.3
4         16.0
          ... 
199995     3.0
199996     7.5
199997    30.9
199998    14.5
199999    14.1
Name: fare_amount, Length: 199999, dtype: float64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
#'''MinMaxScaler is a data preprocessing technique used for feature scaling.
#It transforms features by scaling each feature to a given range, typically between 0 and 1.'''

In [ ]:
sc = MinMaxScaler()
# puting he instance to You are essentially creating a "scaler object" that you can use to apply Min-Max scaling to your data later on. Think of it like having a tool ready to perform the scaling operation whenever needed.

In [ ]:
x_scale = sc.fit_transform(x)
#making the all fear to fit in the sscalke in th edata set

In [ ]:
x_scale
#prin the fit transfrom fron in the x val

array([[0.90600001, 0.06677805, 0.72782548, 0.5258549 , 0.00480769],
       [0.90600392, 0.06677215, 0.72782654, 0.52587035, 0.00480769],
       [0.90599627, 0.06677945, 0.72783367, 0.52588307, 0.00480769],
       ...,
       [0.90600988, 0.0667886 , 0.72785664, 0.52583745, 0.00961538],
       [0.90600193, 0.06677054, 0.72782909, 0.52583906, 0.00480769],
       [0.90601104, 0.06676741, 0.72782858, 0.52588088, 0.00480769]])

In [ ]:
from sklearn.model_selection import train_test_split
# import the model for traing and tesing

In [ ]:
x_tarin, x_test, y_train, y_test = train_test_split(x_scale, y ,test_size = 0.29,random_state=43)
 #inuting the tarin the traina and test and scale and test puting the test size 0.29 puting the random sate 43

In [ ]:
x_tarin
#print x tarin

array([[0.90599812, 0.06677274, 0.72782875, 0.5258673 , 0.00480769],
       [0.90600496, 0.06676459, 0.72782694, 0.52587004, 0.00480769],
       [0.90601496, 0.06678157, 0.72782724, 0.52587122, 0.00480769],
       ...,
       [0.90600401, 0.06678847, 0.72782625, 0.52585327, 0.00961538],
       [0.90601579, 0.0667868 , 0.72782313, 0.52585369, 0.00480769],
       [0.9059996 , 0.06677459, 0.72782732, 0.52586436, 0.00480769]])

In [ ]:
y_train
#y train

94737     10.5
105950    13.0
20596      5.7
33382      8.1
175090    26.0
          ... 
129083     5.0
125206     6.5
40753     11.7
150849    13.5
14148      4.5
Name: fare_amount, Length: 141999, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression
#import the lineal model and lr

In [ ]:
lr = LinearRegression()
#puting the lg in the lr varible

In [ ]:
lr.fit(x_tarin,y_train)
#fit the the data of train x and y

LinearRegression()

In [ ]:
ypred = lr.predict(x_test)
#preding the y value

In [ ]:
ypred
#printing the yp

array([11.29590386, 11.29627266, 11.58448325, ..., 11.3696047 ,
       11.29654261, 11.44101399])

In [ ]:
lr.coef_
#print the an array of weights estimated by linear regression

array([  1.16355661, -10.01392181, -13.91309513, -32.71411333,
        15.04279654])

In [ ]:
lr.intercept_
#print the intercept of the linear regression model

38.16792918019971

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# importin libary erreoer types

In [ ]:
mean_squared_error(y_test,ypred)
#printing the mean squre error

93.8052032814954

In [ ]:
mean_absolute_error(y_test,ypred)
#printing the mean abslout error

6.028774574002058

In [ ]:
r2_score(y_test, ypred)
#printing the r2 score

0.0001240691772714797